"""Lightweight point cloud viewer for ASCII PLY files generated by OpenNI samples.

Usage:
    python project/src/gemini_windows/pointcloud_viewer.py
    python project/src/gemini_windows/pointcloud_viewer.py path/to/1.ply
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[3]
OPENNI_BIN_DIR = (
    ROOT
    / "gemini深度相机windows资料"
    / "Windows"
    / "Windows"
    / "OpenNI_v2.3.0.85_20220615_1b09bbfd_windows_x64_x86_release"
    / "samples"
    / "bin"
)


def find_latest_ply() -> Path:
    candidates = list(OPENNI_BIN_DIR.glob("*.ply"))
    if not candidates:
        raise FileNotFoundError(
            "未找到 .ply 点云文件。请先运行：\n"
            "python project/src/gemini_windows/run_openni_sample.py pointcloud"
        )
    return max(candidates, key=lambda path: path.stat().st_mtime)


def read_ascii_ply(path: Path) -> tuple[np.ndarray, np.ndarray | None]:
    with path.open("r", encoding="utf-8", errors="ignore") as file:
        first_line = file.readline().strip()
        if first_line != "ply":
            raise ValueError(f"{path} 不是 PLY 文件")

        vertex_count: int | None = None
        properties: list[str] = []
        in_vertex_element = False

        for line in file:
            stripped = line.strip()
            if stripped.startswith("element vertex"):
                vertex_count = int(stripped.split()[-1])
                in_vertex_element = True
                continue
            if stripped.startswith("element ") and not stripped.startswith("element vertex"):
                in_vertex_element = False
            if in_vertex_element and stripped.startswith("property"):
                properties.append(stripped.split()[-1])
                continue
            if stripped == "end_header":
                break

        if vertex_count is None:
            raise ValueError("PLY 文件头中没有 element vertex")
        if vertex_count == 0:
            raise ValueError("PLY 文件中没有有效点，可能当前深度帧有效深度太少")

        rows: list[list[float]] = []
        for _ in range(vertex_count):
            line = file.readline()
            if not line:
                break
            values = line.split()
            if len(values) < 3:
                continue
            rows.append([float(value) for value in values[: len(properties)]])

    data = np.asarray(rows, dtype=np.float32)
    if data.shape[0] == 0:
        raise ValueError("PLY 文件没有可解析的点")

    property_index = {name: idx for idx, name in enumerate(properties)}
    points = data[:, [property_index["x"], property_index["y"], property_index["z"]]]

    color_names = ("red", "green", "blue")
    if all(name in property_index for name in color_names):
        colors = data[:, [property_index[name] for name in color_names]]
        colors = np.clip(colors, 0, 255).astype(np.uint8)
    else:
        colors = None

    return points, colors


def downsample(points: np.ndarray, colors: np.ndarray | None, max_points: int) -> tuple[np.ndarray, np.ndarray | None]:
    if points.shape[0] <= max_points:
        return points, colors
    indices = np.linspace(0, points.shape[0] - 1, max_points, dtype=np.int64)
    sampled_colors = colors[indices] if colors is not None else None
    return points[indices], sampled_colors


def depth_colors(points: np.ndarray) -> np.ndarray:
    z = points[:, 2]
    z_min, z_max = np.percentile(z, [2, 98])
    t = np.clip((z - z_min) / max(z_max - z_min, 1.0), 0.0, 1.0)

    red = np.clip(255 * (1.8 * t - 0.25), 0, 255)
    green = np.clip(255 * (1.0 - np.abs(t - 0.5) * 1.8), 0, 255)
    blue = np.clip(255 * (1.2 - 1.5 * t), 0, 255)
    return np.stack([red, green, blue], axis=1).astype(np.uint8)


def rotation_matrix(yaw: float, pitch: float) -> np.ndarray:
    cy, sy = math.cos(yaw), math.sin(yaw)
    cp, sp = math.cos(pitch), math.sin(pitch)
    yaw_mat = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]], dtype=np.float32)
    pitch_mat = np.array([[1, 0, 0], [0, cp, -sp], [0, sp, cp]], dtype=np.float32)
    return pitch_mat @ yaw_mat


def render_points(
    screen,
    points: np.ndarray,
    colors: np.ndarray,
    yaw: float,
    pitch: float,
    zoom: float,
    point_size: int,
) -> None:
    import pygame

    width, height = screen.get_size()
    screen.fill((8, 10, 14))

    rotated = points @ rotation_matrix(yaw, pitch).T
    extent = np.percentile(np.linalg.norm(points[:, :2], axis=1), 98)
    scale = min(width, height) * 0.42 * zoom / max(extent, 1.0)

    xs = (rotated[:, 0] * scale + width / 2).astype(np.int32)
    ys = (-rotated[:, 1] * scale + height / 2).astype(np.int32)

    mask = (xs >= 0) & (xs < width) & (ys >= 0) & (ys < height)
    xs = xs[mask]
    ys = ys[mask]
    visible_colors = colors[mask]

    order = np.argsort(rotated[:, 2][mask])
    xs = xs[order]
    ys = ys[order]
    visible_colors = visible_colors[order]

    pixels = pygame.surfarray.pixels3d(screen)
    for dx in range(point_size):
        for dy in range(point_size):
            px = np.clip(xs + dx, 0, width - 1)
            py = np.clip(ys + dy, 0, height - 1)
            pixels[px, py] = visible_colors
    del pixels


def run_viewer(path: Path, max_points: int) -> None:
    import pygame

    raw_points, raw_colors = read_ascii_ply(path)
    raw_points, raw_colors = downsample(raw_points, raw_colors, max_points)

    center = np.median(raw_points, axis=0)
    points = raw_points - center

    if raw_colors is None or np.unique(raw_colors[: min(len(raw_colors), 1000)], axis=0).shape[0] <= 1:
        colors = depth_colors(raw_points)
        color_mode = "depth"
    else:
        colors = raw_colors
        color_mode = "ply"

    pygame.init()
    screen = pygame.display.set_mode((1100, 760), pygame.RESIZABLE)
    pygame.display.set_caption(f"Gemini PointCloud Viewer - {path.name}")
    font = pygame.font.SysFont("Consolas", 18)

    yaw = 0.0
    pitch = -0.25
    zoom = 1.0
    point_size = 2
    dragging = False
    last_mouse = (0, 0)
    clock = pygame.time.Clock()

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_r:
                    yaw, pitch, zoom = 0.0, -0.25, 1.0
                elif event.key in (pygame.K_EQUALS, pygame.K_PLUS):
                    point_size = min(point_size + 1, 8)
                elif event.key == pygame.K_MINUS:
                    point_size = max(point_size - 1, 1)
                elif event.key == pygame.K_s:
                    pygame.image.save(screen, str(path.with_suffix(".viewer.png")))
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1:
                    dragging = True
                    last_mouse = event.pos
                elif event.button == 4:
                    zoom *= 1.12
                elif event.button == 5:
                    zoom /= 1.12
            elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
                dragging = False
            elif event.type == pygame.MOUSEMOTION and dragging:
                x, y = event.pos
                lx, ly = last_mouse
                yaw += (x - lx) * 0.008
                pitch += (y - ly) * 0.008
                pitch = max(min(pitch, 1.45), -1.45)
                last_mouse = event.pos

        render_points(screen, points, colors, yaw, pitch, zoom, point_size)

        info_lines = [
            f"PLY: {path.name}",
            f"points: {len(points)} / raw: {len(raw_points)}  color: {color_mode}",
            "mouse drag: rotate | wheel: zoom | +/-: point size | R: reset | S: save | Esc: quit",
        ]
        y = 12
        for line in info_lines:
            text = font.render(line, True, (230, 235, 245))
            screen.blit(text, (14, y))
            y += 24

        pygame.display.flip()
        clock.tick(30)

    pygame.quit()


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualize Gemini/OpenNI ASCII PLY point cloud")
    parser.add_argument("ply", nargs="?", help="PLY file path. If omitted, latest OpenNI sample PLY is used.")
    parser.add_argument("--max-points", type=int, default=120_000, help="maximum points rendered")
    args = parser.parse_args()

    ply_path = Path(args.ply) if args.ply else find_latest_ply()
    if not ply_path.exists():
        raise FileNotFoundError(ply_path)

    print(f"打开点云文件: {ply_path}")
    run_viewer(ply_path, args.max_points)


if __name__ == "__main__":
    main()

